# NumPy and Math

In [2]:
import numpy as np

In [3]:
python_list = [1, 2, 3, 4, 5]

#Create a numpy array from a list
numpy_array = np.array(python_list)
print(numpy_array)

[1 2 3 4 5]


In [4]:
oned_shape = numpy_array.shape
oned_size = numpy_array.size
oned_type = numpy_array.dtype

print('1D NumPy Array:')
print("Array:", numpy_array)
print(f'Shape: {oned_shape}')
print(f'Size: {oned_size}')
print(f'DataType: {oned_type}')

1D NumPy Array:
Array: [1 2 3 4 5]
Shape: (5,)
Size: 5
DataType: int64


In [6]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([2, 4, 6, 8])

In [7]:
addition = arr1 + arr2
print(addition)

[12 24 36 48]


In [8]:
subtraction = arr1 - arr2
print(subtraction)

[ 8 16 24 32]


In [9]:
multiplication = arr1 * arr2
print(multiplication)
print(multiplication.dtype)

[ 20  80 180 320]
int64


In [10]:
# division = arr1 // arr2 # creates an int

division = arr1 / arr2 # creates an float
print(division)
print(division.dtype)

[5. 5. 5. 5.]
float64


In [11]:
data = np.array([85, 90, 78, 92, 88, 85, 95])

# Mean, Median
# Std, Variance, Range
data_mean = np.mean(data)
data_median = np.median(data)
data_std = np.std(data)
data_variance = np.var(data)
data_range = np.max(data) - np.min(data)

print(f'Mean: {data_mean}')
print(f'Median: {data_median}')
print(f'StDev: {data_std}')
print(f'Variance: {data_variance}')
print(f'Data Range: {data_range}')

Mean: 87.57142857142857
Median: 88.0
StDev: 5.150787536377128
Variance: 26.53061224489796
Data Range: 17


In [12]:
# Slicing and Indexing
sliced_array = numpy_array[0:3]

index_condition = numpy_array > 3 # creates an array of boolean values based on the condition

index_condition_array = numpy_array[numpy_array > 3] # grabbed (sliced) items from array based on condition

print('Sliced Array', sliced_array)
print('OG Array',numpy_array)
print('Array based on condition', index_condition)
print(index_condition_array)

Sliced Array [1 2 3]
OG Array [1 2 3 4 5]
Array based on condition [False False False  True  True]
[4 5]


In [13]:
combined_result = numpy_array[1:4][numpy_array[1:4] > 3]
print('OG Array',numpy_array)
print('Combined Array:', combined_result)

OG Array [1 2 3 4 5]
Combined Array: [4]


In [14]:
temp_data = np.array([22.3, 23.1, 24.5, 25.8, 23.6, 26.7, 27.9, 29.2, 30.5, 24.7, 23.4, 22.1, 25.3, 26.4, 28.7, 29.8, 31.2, 32.4, 30.7, 29.5, 27.8, 26.6, 23.9, 22.5, 24.1, 25.7, 27.3, 29.6, 31.0, 33.1, 31.9])

In [15]:
mean_temp = np.mean(temp_data)
median_temp = np.median(temp_data)
std_dev_temp = np.std(temp_data)

print(f'Mean: {mean_temp}')
print(f'Median: {median_temp}')
print(f'Std Dev: {std_dev_temp}')

Mean: 27.138709677419353
Median: 26.7
Std Dev: 3.221668313492935


In [16]:
temp_in_f = (temp_data * 9/5) + 32
print(temp_in_f)

[72.14 73.58 76.1  78.44 74.48 80.06 82.22 84.56 86.9  76.46 74.12 71.78
 77.54 79.52 83.66 85.64 88.16 90.32 87.26 85.1  82.04 79.88 75.02 72.5
 75.38 78.26 81.14 85.28 87.8  91.58 89.42]


In [17]:
hot_days = temp_data[temp_data > 30]
print('Hot Temp Days:', hot_days)
print('Num of Hot Days:', len(hot_days))

Hot Temp Days: [30.5 31.2 32.4 30.7 31.  33.1 31.9]
Num of Hot Days: 7


In [18]:
base_temp = 20
cooling_degrees_total = np.sum(np.maximum(temp_data - base_temp, 0))

print('Cooling Degrees:', cooling_degrees_total)

Cooling Degrees: 221.3
