# Data Type Objects in NumPy

In [1]:
import numpy as np

In [2]:
#Create a NumPy array with dtype int32
arr_int = np.array([1, 2, 3, 4], dtype='int32')
print(arr_int)
print(arr_int.dtype)

[1 2 3 4]
int32


In [3]:
#Create a NumPy array with dtype float64
arr_float = np.array([1.5, 2.5, 3.5], dtype='float64')
print(arr_float)
print(arr_float.dtype)

[1.5 2.5 3.5]
float64


In [4]:
#One‑Dimensional Array
#Create a 1D array from 1 to 5
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [5]:
arr = np.arange(1, 6)
print(arr)

[1 2 3 4 5]


In [6]:
#NumPy Operations
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print("Addition:", arr1 + arr2)
print("Subtraction:", arr1 - arr2)
print("Multiplication:", arr1 * arr2)
print("Division:", arr1 / arr2)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


In [7]:
#Dot product
dot_product = np.dot(arr1, arr2)
print("Dot Product:", dot_product)

Dot Product: 32


In [8]:
#Mean, Median, Standard Deviation
print("Mean:", np.mean(arr1))
print("Median:", np.median(arr1))
print("Standard Deviation:", np.std(arr1))

Mean: 2.0
Median: 2.0
Standard Deviation: 0.816496580927726
